config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  get 'customers/alphabetized'

  get 'customers/missing_email'

  #resources :customers, only: [:index]

  root to: 'customers#index'
  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  validates :full_name, :phone_number, presence: true
  validates :full_name, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: '')
  end

  private
  def customer_params
    params.require(:customer_params).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/common/_header.html.erb
<header>
  <br>
  <div class="container">
  <div class="notification is-dark">
  <nav class="level">
    <div class="level-item has-text-centered">
      <div>
        <p class="subtitle is-5">
          <%= link_to "Home", root_path%>
        </p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="subtitle is-5">
          <%= link_to 'Alphabetized', customers_alphabetized_path %>
        </p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="subtitle is-5">
          <%= link_to 'Missing Email', customers_missing_email_path %>
        </p>
      </div>
    </div>
  </nav>
  </div>
  </div>
</header>

app/views/customers/_customer.html.erb
<div class="cust">
  <h2><%= customer.full_name %></h2>
  <br/>
  <% if customer.image.present? %>
      <p><%= image_tag customer.image.variant(resize_to_limit: [290, 300]).processed  %></p>
    <% end %>
  <%# <% if customer.image.present?%>
    <%# <div class="img">
      <figure class="image is-128x128">
        <img src="https://bulma.io/images/placeholders/128x128.png">
      </figure> %>
      <%# <p class="img"><%= image_tag customer.image.variant(resize_to_limit: [300, 300], ) %>
      <%# <%= image_tag(customer.image, :alt => customer.full_name) %>
    <%# </div> %>
  <%# <% end%>
  <p><strong>Phone Number: </strong><%= customer.phone_number %></p>
  <p><strong>Email:</strong> <%= customer.email_address %></p>

</div>

app/views/customers/alphabetized.html.erb
<h1 class="ml-5 title is-2">Customers: Alphabetized</h1>

<p><%= render partial: 'customers/customer', collection: @customers %></p>

app/views/customers/index.html.erb
<h1 class="ml-5 title is-2">All Customers</h1>

<p><%= render partial: 'customers/customer', collection: @customers,
  as: 'customer' %></p>

app/views/customers/missing_email.html.erb
<h1 class="ml-5 title is-2">Customers : Missing Emails</h1>
<p><%= render partial: 'customers/customer', collection: @customers %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <section class="section">
      <div class="container">
        <%= yield %>
        <br>
      </div>
    </section>
  </body>
</html>